/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpirituelRouteImport } from './routes/spirituel'
import { Route as PaiementRouteImport } from './routes/paiement'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as CoursRouteImport } from './routes/cours'
import { Route as ArabeRouteImport } from './routes/arabe'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatutTransactionIdRouteImport } from './routes/statut.$transactionId'
import { Route as RecuReferenceRouteImport } from './routes/recu.$reference'
import { Route as AdminPaiementsRouteImport } from './routes/admin.paiements'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicIpayWebhookRouteImport } from './routes/api/public/ipay-webhook'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SpirituelRoute = SpirituelRouteImport.update({
  id: '/spirituel',
  path: '/spirituel',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementRoute = PaiementRouteImport.update({
  id: '/paiement',
  path: '/paiement',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursRoute = CoursRouteImport.update({
  id: '/cours',
  path: '/cours',
  getParentRoute: () => rootRouteImport,
} as any)
const ArabeRoute = ArabeRouteImport.update({
  id: '/arabe',
  path: '/arabe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatutTransactionIdRoute = StatutTransactionIdRouteImport.update({
  id: '/statut/$transactionId',
  path: '/statut/$transactionId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuReferenceRoute = RecuReferenceRouteImport.update({
  id: '/recu/$reference',
  path: '/recu/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaiementsRoute = AdminPaiementsRouteImport.update({
  id: '/admin/paiements',
  path: '/admin/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIpayWebhookRoute = ApiPublicIpayWebhookRouteImport.update({
  id: '/api/public/ipay-webhook',
  path: '/api/public/ipay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arabe': typeof ArabeRoute
  '/cours': typeof CoursRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/paiement': typeof PaiementRoute
  '/spirituel': typeof SpirituelRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/recu/$reference': typeof RecuReferenceRoute
  '/statut/$transactionId': typeof StatutTransactionIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/ipay-webhook': typeof ApiPublicIpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arabe': typeof ArabeRoute
  '/cours': typeof CoursRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/paiement': typeof PaiementRoute
  '/spirituel': typeof SpirituelRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/recu/$reference': typeof RecuReferenceRoute
  '/statut/$transactionId': typeof StatutTransactionIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/ipay-webhook': typeof ApiPublicIpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arabe': typeof ArabeRoute
  '/cours': typeof CoursRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/paiement': typeof PaiementRoute
  '/spirituel': typeof SpirituelRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/recu/$reference': typeof RecuReferenceRoute
  '/statut/$transactionId': typeof StatutTransactionIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/ipay-webhook': typeof ApiPublicIpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arabe'
    | '/cours'
    | '/inscription'
    | '/login'
    | '/mcp'
    | '/paiement'
    | '/spirituel'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/paiements'
    | '/recu/$reference'
    | '/statut/$transactionId'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/ipay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arabe'
    | '/cours'
    | '/inscription'
    | '/login'
    | '/mcp'
    | '/paiement'
    | '/spirituel'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/paiements'
    | '/recu/$reference'
    | '/statut/$transactionId'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/ipay-webhook'
  id:
    | '__root__'
    | '/'
    | '/arabe'
    | '/cours'
    | '/inscription'
    | '/login'
    | '/mcp'
    | '/paiement'
    | '/spirituel'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/paiements'
    | '/recu/$reference'
    | '/statut/$transactionId'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/ipay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArabeRoute: typeof ArabeRoute
  CoursRoute: typeof CoursRoute
  InscriptionRoute: typeof InscriptionRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PaiementRoute: typeof PaiementRoute
  SpirituelRoute: typeof SpirituelRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminPaiementsRoute: typeof AdminPaiementsRoute
  RecuReferenceRoute: typeof RecuReferenceRoute
  StatutTransactionIdRoute: typeof StatutTransactionIdRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicIpayWebhookRoute: typeof ApiPublicIpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spirituel': {
      id: '/spirituel'
      path: '/spirituel'
      fullPath: '/spirituel'
      preLoaderRoute: typeof SpirituelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiement': {
      id: '/paiement'
      path: '/paiement'
      fullPath: '/paiement'
      preLoaderRoute: typeof PaiementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cours': {
      id: '/cours'
      path: '/cours'
      fullPath: '/cours'
      preLoaderRoute: typeof CoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arabe': {
      id: '/arabe'
      path: '/arabe'
      fullPath: '/arabe'
      preLoaderRoute: typeof ArabeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statut/$transactionId': {
      id: '/statut/$transactionId'
      path: '/statut/$transactionId'
      fullPath: '/statut/$transactionId'
      preLoaderRoute: typeof StatutTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recu/$reference': {
      id: '/recu/$reference'
      path: '/recu/$reference'
      fullPath: '/recu/$reference'
      preLoaderRoute: typeof RecuReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/paiements': {
      id: '/admin/paiements'
      path: '/admin/paiements'
      fullPath: '/admin/paiements'
      preLoaderRoute: typeof AdminPaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ipay-webhook': {
      id: '/api/public/ipay-webhook'
      path: '/api/public/ipay-webhook'
      fullPath: '/api/public/ipay-webhook'
      preLoaderRoute: typeof ApiPublicIpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArabeRoute: ArabeRoute,
  CoursRoute: CoursRoute,
  InscriptionRoute: InscriptionRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PaiementRoute: PaiementRoute,
  SpirituelRoute: SpirituelRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminPaiementsRoute: AdminPaiementsRoute,
  RecuReferenceRoute: RecuReferenceRoute,
  StatutTransactionIdRoute: StatutTransactionIdRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicIpayWebhookRoute: ApiPublicIpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
